# Generated by Django 4.2.5 on 2023-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_sellerprofile_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_seller',
            field=models.BooleanField(default=True),
        ),
    ]
