# Generated by Django 4.2.5 on 2023-10-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_', '0002_cartitem_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
